config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('allauth.urls')),
    path('accounts/',include('accounts.urls')),
    path('',include('musics.urls')),
    path('',include('pages.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# handler404 = "musics.views.eror_404"

musics/urls.py
from django.urls import path
from .import views
urlpatterns = [
    #musics
    path('',views.main_page_view,name='main_page'),
    path('music/<int:pk>/',views.music_detail_view,name='detail_view'),
    path('music/add_music/',views.music_add_view,name='add_music'),
    #playlist
    path('playlists/',views.all_user_playlists,name='playlists'),
    path('playlists/delete/<int:pk>/',views.all_user_playlist_delete_view,name='playlist_delete'),
    path('playlists/<str:playlist_name>/',views.playlist_detail,name='playlist_songs'),
    path('playlists/add/', views.play_list_add, name='add_playlist'),
    path('playlists/song_add/<str:playlist_name>/', views.play_list_song_add, name='add_playlist_song'),
    #favorits
    path('favorits/',views.favorit_songs,name='favorit_songs'),
    #search
    path('search_answer/<str:word>/',views.search_view,name='search'),
    #all songs
    path('all_songs/',views.all_songs,name='all_songs'),
    #album
    path('albums/',views.album_list_view,name='albums'),
    path('albums/<int:pk>/',views.album_detail_view,name='album_songs'),
    path('albums/add/',views.album_add_view,name='add_album'),
    # artists
    path('artists/', views.artist_view, name='artists'),
    path('artists/<str:artist>/', views.artist_songs_view, name='artist_songs'),
    path('add_artist/',views.artist_add_view,name='add_artist'),
    # genres and instruments
    path('genres/<str:name>/',views.genres_view,name='genres'),
    path('instruments/<str:name>/',views.instrument_view,name='instruments'),
    # by language
    path('music/english/', views.english_songs, name='english'),
    path('music/farsi/', views.farsi_songs, name='farsi'),

]

pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('contact_us/', views.ContactView.as_view(), name='contact'),
    path('about_us/', views.AboutUsView.as_view(), name='about'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
]

musics/models.py
from django.db import models
from django.urls import reverse
from sorl.thumbnail import ImageField
from accounts.models import CustomUser
from django.contrib.auth import get_user_model


class Music(models.Model):
    RATING_CHOICES = (
        (1, 'poor'),
        (2, 'average'),
        (3, 'good'),
        (4, 'very good'),
        (5, 'excellent'),
    )

    title = models.CharField(max_length=50)
    Artist = models.ForeignKey('Artists', on_delete=models.CASCADE, null=True)
    language = models.CharField(choices=(
        ('iri', 'farsi'),
        ('eng', 'english'),),
        max_length=3, blank=True)
    audio = models.FileField(upload_to='audios/', blank=True)
    cover = ImageField(upload_to='music_covers/', blank=True)
    download_link = models.CharField(max_length=100)
    rating = models.IntegerField(choices=RATING_CHOICES, default=1)
    genres = models.CharField(choices=CustomUser.MUSIC_CATG_CHOICES, max_length=2, default=1)
    instrument_used = models.CharField(choices=CustomUser.MUSIC_instrument_CHOICES, max_length=2, blank=True)
    Album = models.ForeignKey('Album', on_delete=models.CASCADE, blank=True, null=True)
    view_number = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('detail_view', args=[self.id])



class Favorits(models.Model):
    id = models.AutoField(primary_key=True)
    song = models.ForeignKey(Music, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), models.CASCADE)
    is_favorit = models.BooleanField(default=False)


class PlayList(models.Model):
    playlist_name = models.CharField(max_length=100)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    datetime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.playlist_name


class PlaylistSongs(models.Model):
    playlist = models.ForeignKey(PlayList, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    song_name = models.CharField(max_length=100)
    audios = models.FileField(upload_to='playlist_audios/')


class Album(models.Model):
    Album_name = models.CharField(max_length=100)
    Artist = models.ForeignKey('Artists', on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    datetime = models.DateTimeField(auto_now_add=True)
    genres = models.CharField(choices=CustomUser.MUSIC_CATG_CHOICES, max_length=2, blank=True)
    cover = ImageField(upload_to='album_covers/')

    def get_absolute_url(self):
        return reverse('album_songs', args=[self.id])

    def __str__(self):
        return self.Album_name



class AlbumSongs(models.Model):
    Album = models.ForeignKey(Album, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    song = models.ForeignKey(Music, on_delete=models.CASCADE)

class Artists(models.Model):
    name = models.CharField(max_length=100)
    date_of_birth = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.name


class View(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, blank=True, null=True)
    ip = models.CharField(max_length=20)
    song = models.ForeignKey(Music, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.song}:{self.ip}'

musics/forms.py
from django.forms import ModelForm

from .models import *


class MusicForm(ModelForm):
    class Meta:
        model = Music
        fields = ['title', 'Artist', 'language', 'audio', 'cover',
                  'download_link', 'rating', 'genres', 'instrument_used', 'Album', ]

class FavForm(ModelForm):
    class Meta:
        model = Favorits
        fields = ['is_favorit', ]


class PlaylistForm(ModelForm):
    class Meta:
        model = PlayList
        fields = ['playlist_name']


class PlaylistSongsForm(ModelForm):
    class Meta:
        model=PlaylistSongs
        fields=['song_name','audios']


class AlbumForm(ModelForm):
    class Meta:
        model = Album
        fields = ['Album_name', 'Artist', 'genres', 'cover', ]


class ArtistForm(ModelForm):
    class Meta:
        model = Artists
        fields = ['name','date_of_birth']

musics/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required,permission_required
from django.shortcuts import get_object_or_404
from django.db.models import Q
from django.conf import settings
from django.core.paginator import Paginator
from ipware import get_client_ip
from django.contrib.auth import get_user_model


import os

from .forms import *
from .models import *
from .decorators import user_passes_test
from .toolfuncs import pick_random,check_user_and_adder,check_fav_list,add_user_to_group



def main_page_view(request):
    #vars
    word = ''
    random_suggestion = []
    all_musics = Music.objects.all() # all songs
    add_user_to_group()
    # geting random songs pick_random is a function wich has been  defined in the bottom
    random_musics = pick_random(all_musics,5)
    up_rates = Music.objects.filter(rating=5)
    # if user is authenticated we will show some suggestions by its favorites which had chosen in the authentication
    if request.user.is_authenticated:
        user = get_user_model().objects.get(username=request.user) # finding the user
        suggestions = Music.objects.filter(instrument_used=user.favorite_instrument,genres=user.favorite_musics)
        # pick 5 song from suggestion there might be less than 5 , so we will show 5 or less
        random_suggestion = pick_random(suggestions,5)
    # if user search something
    if request.method == 'POST':
        word = request.POST.get('search')
        return redirect('search', word=word)

    return render(request, 'musics/musics_list_view_temp.html',
                  context={'random': random_musics,
                           'up_rates': up_rates,
                           'random_sugg': random_suggestion})
#-=====================================================================
def music_detail_view(request, pk):  # any user can access detail view
    random_sugg = []
    # it gets the user ip adr
    ip = get_client_ip(request)[0]
    # getting music by the pk
    music = get_object_or_404(Music, pk=pk)
    all = Music.objects.all()
    #==================VIEWS MANAGMENT==========
    # to prevent eror when there's no object of this model(no view for the song)
    if len(View.objects.all())!=0 :
        # cheking if this user has any views of this song
        all_user_views = View.objects.filter(Q(user=request.user)|Q(ip=ip),song=music)
        # if this user has no view for this song we can add the view wich means th user is uniqe
        if len(all_user_views) == 0:
            View.objects.create(user=request.user,ip=ip,song=music)
    else:# we add the view if views are 0
        View.objects.create(user=request.user, ip=ip, song=music)
    # getting views for the music
    music_views = View.objects.filter(song=music)

    #=============SUGGESTION MANAGMENT==================
    # suggest some songs that are not duplicated from songs when user is authenticated
    if request.user.is_authenticated:
        suggestions = [i for i in Music.objects.filter(Q(Artist=music.Artist)|Q(genres=music.genres)) if i.title != music.title]#getting the user's suggestions
        if len(suggestions) <3 and len(suggestions) != 0:
            # we will pick from all if the music suggs are less than 3
            random_suggestions = pick_random(all,3)
        # chosing random songs from suggesstions
        if len(suggestions) >=3:
            random_suggestions = pick_random(suggestions,3)

    # to add the song to favorits only for authenticated users
    if request.method == 'POST' and request.user.is_authenticated:
        form = FavForm(request.POST)
        if form.is_valid():
            # checks if the song is already in the favorites list
            if check_fav_list(request, music):
                is_fav = form.save(commit=False)
                is_fav.user = request.user
                is_fav.song = music
                is_fav.save()
    else:
        form = FavForm()

    return render(request, 'musics/musics_detail_view_temp.html',
                  {'music': music,
                   'form': form,
                   'isin': check_fav_list(request, music),
                   'sugg':random_sugg,'views':len(music_views)
                   })
#=======================================
@login_required()
@permission_required('can_add_music',raise_exception=True)
def music_add_view(request):
    if request.method == 'POST':
        form = MusicForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('all_songs')
    else:
        form = MusicForm()
    return render(request,'musics/add_music_page.html',{'form':form})

#======================================
@login_required()
def favorit_songs(request):
    songs = Music.objects.filter(favorits__user=request.user, favorits__is_favorit=True).distinct()
    # the delete option
    if request.method == "POST":
        # getting song_id witch has sent as the name
        # @login_required() of our delete button[csrf_token,song_id]
        song_id = list(request.POST.keys())[1]
        # getting the song with pk , i checked the user and is_favorite for sure
        favorite_song = Favorits.objects.filter(user=request.user, song__id=song_id,is_favorit=True)
        favorite_song.delete()

    return render(request, 'musics/favs.html', {'fav_song': songs})

#======================================
def all_user_playlists(request):
    # getting all playlists of this user
    playlists = PlayList.objects.filter(user=request.user)
    if request.method == "POST":
        # getting playlist id which has sent as the name of button in html file
        playlist_id = list(request.POST.keys())[1]
        return redirect('playlist_delete',playlist_id)
    return render(request, 'musics/playlist_page.html', {'playlist': playlists})

#==========================================
@user_passes_test(check_user_and_adder,model_obj=PlayList,raise_exception=True,url_input_obj_name='pk')
#delete the playlist object by pk
def all_user_playlist_delete_view(request,pk):
    playlist = get_object_or_404(PlayList,pk=pk)
    if request.method =='POST':
        playlist.delete()
        return redirect('playlists')
    return render(request,'musics/playlist_delete_temp.html',{'playlist':playlist})
#=============================================

@user_passes_test(check_user_and_adder,model_obj=PlayList,raise_exception=True,url_input_obj_name='playlist_name')
@login_required()
def playlist_detail(request, playlist_name):
    songs = PlaylistSongs.objects.filter(playlist__playlist_name=playlist_name,playlist__user=request.user)  # playlist is a FK to playlist table
    playlist = get_object_or_404(PlayList,playlist_name=playlist_name)  # getting the playlist for adding music at later
    # delete the playlist
    if request.method == "POST":
        # getting song id which has sent as the name of the delete button
        playlist_id = list(request.POST.keys())[1]
        song = PlaylistSongs.objects.filter(pk=playlist_id,user=request.user)
        # getting the name of the song path to delete
        song_path = song[0].audios.name
        song.delete()  # deleting the song object
        os.remove(os.path.join(settings.MEDIA_ROOT, song_path))  # deleting the song file in the path wich had defined in setting

    return render(request, 'musics/playlist_songs_page.html',
                  {'songs': songs, 'pl_name': playlist_name, 'playlist': playlist})

#=-=============================================================

@login_required()
def play_list_add(request):
    if request.method == "POST":
        form = PlaylistForm(request.POST)
        if form.is_valid():
            playlist = form.save(commit=False)
            playlist.user = request.user
            playlist.save()
            return redirect('playlists')
    else:
        form = PlaylistForm()
    return render(request, 'musics/add_playlist_temp.html', {'form': form})
#=================================================================
@login_required()
@user_passes_test(check_user_and_adder,raise_exception=True,url_input_obj_name='playlist_name',model_obj=PlayList)
def play_list_song_add(request, playlist_name):
    playlist = get_object_or_404(PlayList, playlist_name=playlist_name)
    if request.method == "POST":
        form = PlaylistSongsForm(request.POST)
        if form.is_valid():
            song = form.save(commit=False)
            song.user = request.user
            song.playlist = playlist
            song.save()
            return redirect('add_playlist_song')
    else:
        form = PlaylistSongsForm()
    return render(request, 'musics/add_playlist_songs_temp.html', {'form': form, 'playlist': playlist})

#======================================================

def search_view(request, word):
    object_list = []
    # if user search somthing in the search page
    if request.method == 'POST':
        word = request.POST.get('search')
        object_list = Music.objects.filter(
            Q(title__icontains=word.strip().lower()) | Q(Artist__name__icontains=word.strip().lower()) | Q(
                genres__icontains=word.strip().lower()))
    # for the response to search from other pages
    if request.method == 'GET':
        object_list = Music.objects.filter(
            Q(title__icontains=word.strip().lower()) | Q(Artist__name__icontains=word.strip().lower()) | Q(
                genres__icontains=word.strip().lower()))
    return render(request, 'musics/search_answer.html', {'song': object_list, 'word': word})
#======================================================

def all_songs(request):
    musics = Music.objects.all()
    # paginator configuration
    paginator = Paginator(musics, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'musics/song_and_instrument.html', {'page_obj': page_obj, 'catg': 'all songs'})

#==================================================

musics/templates/musics/add_album_page.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %} Add album {% endblock %}


{% block content %}

    <div>
        <h2>Add album</h2>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success">Submit</button>


        </form>


    </div>





{% endblock content %}

musics/templates/musics/add_artist_page.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %} Add artist {% endblock %}


{% block content %}

    <div>
        <h2>Add artist</h2>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success">Submit</button>


        </form>


    </div>





{% endblock content %}

musics/templates/musics/add_music_page.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %} Add song {% endblock %}


{% block content %}

    <div>
        <h2>Add song</h2>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success">Submit</button>


        </form>


    </div>





{% endblock content %}

musics/templates/musics/add_playlist_temp.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %} Add playlist{% endblock %}


{% block content %}

    <div>
        <h1>add playlist for {{ user.username }}</h1>

        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit">Submit</button>


        </form>


    </div>





{% endblock content %}

musics/templates/musics/album_detail_view_temp.html
{% extends '_base.html' %}
{% load thumbnail %}




{% block title %} hello{% endblock %}


{% block content %}

    <div class="container mt-9">
        <h2>{{ album.Album_name }}</h2>
        <p class="mt-3">
            {% for song in songs %}



                {% thumbnail song.song.cover "200x200" crop="center" as im %}
                    <a href="{{ song.song.get_absolute_url }}"><img src="{{ im.url }}" width="{{ im.width }}"
                                                                height="{{ im.height }}" alt="..."></a>
                {% endthumbnail %}

            {% endfor %}
        </p>

    </div>


{% endblock content %}

musics/templates/musics/artist_page.html
{% extends '_base.html' %}





{% block title %}artists{% endblock %}





{% block content %}

    <div class="container mt-9">
        <h2>all artists</h2>

            {% for artist in artists %}




                <div>
                    <a href="{% url 'artist_songs' artist.name %}">{{ artist.name }}</a>
                </div>

            {% endfor %}

        {% if user.is_staff %}
        <a href="{% url 'add_artist' %}" class="btn btn-info">add artist</a>

    {% endif %}
    </div>


{% endblock content %}

musics/templates/musics/artist_songs.html
{% extends '_base.html' %}
{% load thumbnail %}

{% block title %}{{ artist.name }}{% endblock title %}




{% block content %}
    <h1>{{ artist.name }}'s songs</h1>
    <div class="container mt-9">
        <p>
            {% for song in songs %}
                {% thumbnail song.cover "200x200" crop='center' as im %}
                    <a href="{{ song.get_absolute_url }}"><img src="{{ im.url }}" width="{{ im.width }}"
                                                            height="{{ im.height }}" alt="..."></a>
                {% endthumbnail %}

            {% endfor %}

        </p>
    {% if user.is_staff %}
        <a href="{% url 'add_music' %}" class="btn btn-info">add song</a>

    {% endif %}
    </div>

{% endblock content %}

musics/templates/musics/favs.html
{% extends '_base.html' %}
{% load thumbnail %}

{% block title %} hello{% endblock %}


{% block content %}

    {% if user.is_authenticated %}
        <h1>Your Favorite songs</h1>
        <div>
            <p>
                {% for a in fav_song %}

                    {% thumbnail a.cover "200x200" crop="center" as im %}
                        <a href="{{ a.get_absolute_url }}"><img src="{{ im.url }}" width="{{ im.width }}"
                                                                height="{{ im.height }}" alt="..."></a>
                        <form method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger" name="{{ a.id }}" value="Remove">Delete
                            </button>
                        </form>
                    {% endthumbnail %}
                {% endfor %}
            </p>
        </div>
    {% endif %}
{% endblock content %}

musics/templates/musics/musics_detail_view_temp.html
{% extends '_base.html' %}
{% load thumbnail %}
{% load crispy_forms_tags %}
{% load static %}


{% block static %}
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
{% endblock static %}

{% block title %} Music|{{music.title }}{% endblock %}


{% block content %}
    <div class=" container mt-9">
        <div class="d-flex justify-content-center">
            <div class="column mt-3 w-sm-75 ">
                <div class="">

                    {% thumbnail music.cover "300x300" crop="center" as im %}
                        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="...">
                    {% endthumbnail %}
                </div>

                <div>

                    <h2 class="card-title">{{ music.title|capfirst }}</h2>
                    <h3 class="card-text">By: <a
                            href="{% url 'artist_songs'  music.Artist.name %}">{{ music.Artist.name }}</a></h3>
                    <h5 class="card-text">{{ music.get_genres_display }}</h5>
                    {% if music.instrument_used %}
                        <h5 class="card-text">Instrument used: {{ music.get_instrument_used_display }}</h5>
                    {% endif %}
                    {% if music.Album %}
                        <h5 class="card-text">album: <a href="{{ music.Album.get_absolute_url }}">{{ music.Album }}</a>
                        </h5>

                    {% endif %}

                    <h5 class="card-text">views: {{ views }}</h5>


                </div>
                <div>
                    <audio controls class="card-text">
                        <source src="{{ music.audio.url }}" type="audio/mpeg">
                    </audio>

                </div>
                <div>
                    {% if user.is_authenticated %}

                        <a href="{{ music.download_link }} " class="btn btn-primary">download</a>
                    {% endif %}
                </div>


                <div style="text-align:-webkit-right;">
                    {% if not isin %}
                        <div style="align-content: baseline">


                            <h3>{{ music.title }} is in <a href="{% url 'favorit_songs' %}">favorits</a></h3>
                            {#                                <a href="{% url 'delete' music.pk %}" class="btn btn-danger"> Delete</a>a#}


                        </div>
                    {% else %}
                        {% if user.is_authenticated %}


                            <form method="post">
                                {% csrf_token %}
                                {{ form|crispy }}
                                <button type="submit">add it to favorits</button>

                            </form>
                        {% else %}
                            <p>login to add favorite & download feature</p>
                            <a href="{% url 'login' %}" class="btn btn-success">Login</a>
                        {% endif %}
                    {% endif %}
                </div>

                <div>
                    {% if sugg %}

                        <h3>suggestions for you</h3>
                        {% for s in sugg %}
                            {% thumbnail s.cover "250x250" crop="center" as im %}
                                <a href="{{ s.get_absolute_url }}"><img src="{{ im.url }}" width="{{ im.width }}"
                                                                        height="{{ im.height }}" alt="..."></a>
                            {% endthumbnail %}

                        {% endfor %}

                    {% endif %}


                </div>

            </div>
        </div>

    </div>






{% endblock content %}

{% block script %}
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>


{% endblock script %}

musics/templates/musics/musics_list_view_temp.html
{% extends '_base.html' %}
{% load thumbnail %}


{% load static %}

{% block title %} hello{% endblock %}

{% block search %}
    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
    <button class="btn btn-outline-success" type="submit">Search</button>
{% endblock search %}


{% block content %}
    <div class="container mt-9">
        <h2>instruments</h2>
        <p class="mt-3">


            <a href="{% url 'instruments' 'piano' %}"><img src="{% static 'icons/piano.jfif' %}" width="200" height="200"
                                             alt=""></a>


            <a href="{% url 'instruments' 'violin' %}"><img src="{% static 'icons/violin.png' %}" width="200" height="200" alt=""></a>


            <a href="{% url 'instruments' 'guitar' %}"><img src="{% static 'icons/guitar.png' %}" width="200" height="200" alt=""></a>

            <a href="{% url 'instruments' 'flute' %}"><img src="{% static 'icons/flute.png' %}" width="200" height="200"
                                             alt=""></a>

        </p>

    </div>

    <div class="container mt-9">
        <h2>categories</h2>
        <p class="mt-3">


            <a href="{% url 'genres' 'pop' %}"><img src="{% static 'icons/pop.png' %}" width="200" height="200"
                                           alt=""></a>


            <a href="{% url 'genres' 'rock' %}"><img src="{% static 'icons/rock.png' %}" width="200" height="200" alt=""></a>


            <a href="{% url 'genres' 'hiphop' %}"><img src="{% static 'icons/hiphop.jfif' %}" width="200" height="200"
                                              alt=""></a>

            <a href="{% url 'genres' 'classic' %}"><img src="{% static 'icons/classic.png' %}" width="200" height="200"
                                               alt=""></a>

        </p>
    </div>
    {% if random_sugg %}

        <div class="container mt-9">
            <h2>for you</h2>
            <p class="mt-3 mb-3">
                {% for rand in random_sugg %}
                    {% thumbnail rand.cover "200x200" crop="center" as im %}
                        <a href="{{ rand.get_absolute_url }}"><img src="{{ im.url }}" width="{{ im.width }}"
                                                                   height="{{ im.height }}" alt="..."></a>
                    {% endthumbnail %}

                {% endfor %}
            </p>

        </div>
    {% endif %}

    <div class="container mt-9">
        <h2>top songs</h2>
        <p class="mt-3 mb-3">
            {% for music in up_rates %}




                {% thumbnail music.cover "200x200" crop="center" as im %}
                    <a href="{{ music.get_absolute_url }}"><img src="{{ im.url }}" width="{{ im.width }}"
                                                                height="{{ im.height }}" alt="..."></a>
                {% endthumbnail %}



            {% endfor %}
        </p>

    </div>
    <div class="container mt-9">
        <h2>random songs</h2>
        <p class="mt-3">
            {% for m in random %}



                {% thumbnail m.cover "200x200" crop="center" as im %}
                    <a href="{{ m.get_absolute_url }}"><img src="{{ im.url }}" width="{{ im.width }}"
                                                            height="{{ im.height }}" alt="..."></a>
                {% endthumbnail %}

            {% endfor %}
        </p>

    </div>



{% endblock content %}

musics/templates/musics/playlist_delete_temp.html
{% extends '_base.html' %}
{% load thumbnail %}

{% block title %} hello{% endblock %}


{% block content %}

    <div>
        <h1>Are you sure you want to delete {{ playlist.playlist_name }}</h1>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Yes Im Sure</button>
        </form>
        <a href="{% url 'playlists'%}" class="btn btn-success">Cancle</a>

    </div>

{% endblock content %}

musics/templates/musics/playlist_songs_page.html
{% extends '_base.html' %}
{% load thumbnail %}

{% block title %} hello{% endblock %}


{% block content %}

    <div>
        {% if songs %}

            <a href="{% url 'add_playlist_song' playlist.playlist_name %}" class="btn btn-info mt-3">add song</a>

            <h1>{{ playlist_name }}</h1>
            {% for song in songs %}
                <h3>{{ song.song_name }}</h3>
                <audio controls>
                    <source src="{{ song.audios.url }}" type="audio/mpeg">
                </audio>
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger" name="{{ song.pk }}">Delete</button>
                </form>
            {% endfor %}
        {% else %}
            <h2>there are'nt any song in this playlist</h2>
            <a href="{% url 'add_playlist_song' playlist.playlist_name %}" class="btn btn-info">add song</a>

        {% endif %}


    </div>


{% endblock content %}

musics/templates/musics/search_answer.html
{% extends '_base.html' %}
{% load thumbnail %}

{% block title %} hello{% endblock %}

{% block search %}
    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
    <button class="btn btn-outline-success" type="submit">Search</button>
{% endblock search %}


{% block content %}


    <div>

        {% if song %}

            <h1>you search answer</h1>

            <p>
                {% for a in song %}


                    {% thumbnail a.cover "200x200" crop="center" as im %}
                        <a href="{{ a.get_absolute_url }}"><img src="{{ im.url }}" width="{{ im.width }}"
                                                                height="{{ im.height }}" alt="..."></a>
                    {% endthumbnail %}



                {% endfor %}
            </p>
        {% else %}
            <h1>nothing found</h1>
            <a href="{% url 'main_page' %}">Musics</a>
        {% endif %}
    </div>












{% endblock content %}