config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('allauth.urls')),
    path('accounts/',include('accounts.urls')),
    path('',include('musics.urls')),
    path('',include('pages.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# handler404 = "musics.views.eror_404"

pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('contact_us/', views.ContactView.as_view(), name='contact'),
    path('about_us/', views.AboutUsView.as_view(), name='about'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    MUSIC_CATG_CHOICES = (
        ('po','pop'),
        ('cl','classic'),
        ('ro','rock'),
        ('hi','hip hop'),
    )
    MUSIC_instrument_CHOICES = (
        ('pi', 'piano'),
        ('vi', 'violin'),
        ('gu', 'guitar'),
        ('fl', 'flute'),
    )

    favorite_musics = models.CharField(choices=MUSIC_CATG_CHOICES,max_length=2)
    favorite_instrument = models.CharField(choices=MUSIC_instrument_CHOICES,max_length=2)

templates/_base.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">






    {% block static %}
    {% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'main_page' %}">
                <img src="{% static 'icons/images.png' %}" alt="" height="30"
                     class="d-inline-block align-text-top">
            </a>
            <a class="navbar-brand" href="{% url 'main_page' %}">Musics</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">


                    <li class="nav-item">


                        <a class="nav-link active" aria-current="page" href="{% url 'albums' %}">Albums</a>

                    </li>
                    <li class="nav-item">


                        <a class="nav-link active" aria-current="page" href="{% url 'all_songs' %}">all songs</a>

                    </li>
                    <li class="nav-item">
                        {% if user.is_authenticated %}

                            <a class="nav-link active" aria-current="page" href="{% url 'profile' %}">profile</a>
                        {% endif %}
                    </li>


                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Authentication
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% if user.is_authenticated %}

                                <li><a href="{% url 'account_logout' %}" class="dropdown-item"><h3>Logout</h3></a></li>
                            {% else %}
                                <li><a href="{% url 'account_login' %}" class="dropdown-item"><h3>Login</h3></a></li>
                                <li><a href="{% url 'account_signup' %}" class="dropdown-item"><h3>Signup</h3></a></li>
                            {% endif %}

                        </ul>
                    </li>
                    <li class="nav-item">
                        {% if user.is_authenticated %}
                            <a class="nav-link" href="{% url 'favorit_songs' %}">My Favorit songs</a>

                        {% endif %}
                    </li>
                    <li class="nav-item">
                        {% if user.is_authenticated %}
                            <a class="nav-link" href="{% url 'playlists' %}">My playlists</a>

                        {% endif %}
                    </li>

                </ul>
                <div>
                    {% if user.is_authenticated %}
                        {% if user.first_name %}

                            <h3>welcome {{ user.first_name }}  </h3>
                        {% else %}
                            <h3>welcome {{ user.username }}  </h3>
                        {% endif %}
                    {% endif %}
                </div>
                <form class="d-flex" method="post">
                    {% csrf_token %}
                    {% block search %}

                    {% endblock search %}
                </form>

            </div>
        </div>
    </nav>

</div>

{% block content %}

{% endblock %}



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
{% block script %}
{% endblock script %}

</body>
</html>

templates/aboutus_page.html
{% extends '_base.html' %}


{% block title %} about Us {% endblock title %}



{% block content %}

    <h1>hi , welcom to web music player </h1>
    <p>im mohammad amin forouzan, django developer . based in iran,isfahan</p>



{% endblock content %}

templates/contactus_page.html
{% extends '_base.html' %}


{% block title %} contact Us {% endblock title %}



{% block content %}

    <h1>you can contact me using my email : </h1>
    <h4>maf081378@gmail.com</h4>
    <h4>you can report bugs or give me your opinions about this website  on my email </h4>


{% endblock content %}

templates/profile_temp.html
{% extends '_base.html' %}

{% block title %}{{ user.username }}'s profile{% endblock title %}



{% block content %}
    <div>
        <h1>{{ user.username }}'s profile</h1>

        <ul>

                <li>first name:{{ user.first_name }}</li>




                <li>last name:{{ user.last_name }}</li>



                <li>favorite music:{{ user.get_favorite_musics_display }}</li>



                <li>favorite music:{{ user.get_favorite_instrument_display }}</li>

            <a href="{% url 'update_profile' user.pk %}" class="btn btn-info mt-3 mb-3">Edit profile</a>
            <li><a href="{% url 'account_set_password' %}" class="btn btn-danger">change password</a></li>
        </ul>
    </div>












{% endblock content %}